### PR TITLE
Add Bits.sub - jonathanrlouie

### PR DESCRIPTION
**Pull request by MaisaMilena**
Update to the new syntax from [Moonad#16](https://github.com/moonad/Moonad/pull/116)

### CODE REVIEW

**Comment by VictorTaelin** [comment]
This is nice, but a bit too long. We should just use the same algorithm as Bits.inc?

**Comment by jonathanrlouie** [comment]
@MaiaVictor I'm not seeing how Bits.sub can use the same algorithm as Bits.inc. Can you elaborate a bit on how that would work?

**Comment by jonathanrlouie** [comment]
Just had a realization. Would this be better?
```
Bits.sub(a: Bits, b: Bits): Bits
  Bits.reverse(Bits.sub.go(a, b, Bits.e))

Bits.sub.go(a: Bits, b: Bits, bits: Bits): Bits
  case b {
    e: case a {
      e: bits,
      o: Bits.sub.go(a.pred, b, Bits.o(bits)),
      i: Bits.sub.go(a.pred, b, Bits.i(bits))
    },
    o: case a {
      e: Bits.sub.go(a, b.pred, Bits.o(bits)),
      o: Bits.sub.go(a.pred, b.pred, Bits.o(bits)),
      i: Bits.sub.go(a.pred, b.pred, Bits.i(bits))
    },
    i: case a {
      e: Bits.e,
      o: Bits.sub.go(a.pred, Bits.inc(b.pred), Bits.i(bits)),
      i: Bits.sub.go(a.pred, b.pred, Bits.o(bits))
    }
  }
```

I also realized that I can't update this branch, since I don't have permissions. Do I need to create a separate PR?

**Comment by VictorTaelin** [comment]
I meant in the sense of creating a `Bits.dec` algorithm and then applying it `n` times. But in retrospect, that will be slow in non-optimal evaluators. Your code is clean and nice. Seems like it is conflicting though. @MaisaMilena can you check if it type-checks and merge?

Thanks for the contrib! (:

**Comment by MaisaMilena** [comment]
@jonathanrlouie can you open a new PR with your solution? As you can't update this PR I will close it.

**Pull request closed without merging**
