### PR TITLE
Parse UTF-8 into String

### PR DESCRIPTION
**Pull request by MaisaMilena**
Follows some functions from [eth-lib](https://github.com/MaiaVictor/eth-lib/blob/master/src/bytes.js) by @MaiaVictor 

- Add functions covering Bytes
- Add tests covering Bytes and some other types
- Has a lot of things going on, sorry

I finally got some good outputs from `Bytes.parse_string`. Still has some things to do. `Bytes.parse_string` is **NOT** working for all cases, but we have some tests passing (check `Bytes.test.parse_string`).

### CODE REVIEW

**Comment by elmattic** [comment]
Hey, thank you @MaisaMilena, this is exactly what I was needing for my Wasm [module](https://github.com/elmattic/Kind/blob/elmattic/wasm/base/Wasm/Reader/name.kind)!

**Comment by VictorTaelin** [comment]
Thanks for the contributions!

@rigille can you review & merge? Also should check if it interacts with the problematic Keccak to hex function we've been discussing before.

**Comment by caotic123** [comment]
Thank you for your great contribution Maisa.
I will approve this later, after some adjustment!

**Comment by MaisaMilena** [comment]
> Hey, thank you @MaisaMilena, this is exactly what I was needing for my Wasm [module](https://github.com/elmattic/Kind/blob/elmattic/wasm/base/Wasm/Reader/name.kind)!

I'm still struggling with some details, but hope to get it all working soon 🙏

**Pull request merged**
