### PR TITLE
Refactor polymorphic types to use angle brackets

### PR DESCRIPTION
**Pull request by elmattic**
This PR refactors following types to use angle brackets:

- App
- App.Action
- Array
- BitsMap
- Decidable
- Either
- Equal
- Fin
- Functor
- GMap
- GSet
- IO
- Kind.Check
- List
- Maybe
- Monad
- Pair
- Parser.Reply
- Queue
- The
- Vector

I can remove types if needed or add some others.

### CODE REVIEW

**Comment by elmattic** [comment]
Btw [here's](https://gist.github.com/elmattic/e3817b670a53bea45e846312809319cf) the Lua script I have used, if you prefer use it and convert to angle brackets yourself.

**Comment by VictorTaelin** [comment]
Can this be merged? What is the state of it? @rigille can you have a look?

**Comment by rigille** [comment]
i feel intimidated by those conflicts kkkk
i'll follow guillaume's suggestion and test the script in `master`

**Comment by VictorTaelin** [comment]
Perhaps we should just re-run the script and merge imediatelly?

**Comment by elmattic** [comment]
> Perhaps we should just re-run the script and merge imediatelly?

Yeah I think it would be better to re-run the script on tip of master!

**Pull request closed without merging**
