### PR TITLE
Add C WASM version of new runtime

### PR DESCRIPTION
**Pull request by michaelforney**
The C program does not use the standard library, so does not need emscripten, wasi, or anything like that. `runtime_wasm.reduce` creates a new WebAssembly.Memory, and writes an array of pointers, whose indices are the RefId, and whose values are pointers to Term `[ptr, len, mem...]`, which are written in order after the RefId array. Finally, an array of four `uint32_t` is reserved for the Result, then `fm_reduce` is called with a pointer to the Result struct, a pointer to the definitions table, the RefId of the term to reduce, and a pointer to the rest of the memory (where the reduction takes place).

Right now, the memory is expected to be big enough to hold the entire reduction. In the future, we could have a check before adding to the mem array, that if the end address would cross the 64k boundary (WASM page size), call `__builtin_wasm_memory_grow` to expand it.

The `back` array is implemented as a fixed size array on the stack of size 1024. This is probably okay since it is essentially the "stack" of the reduction. We could potentially even just write `fm_reduce` recursively, and just use the WASM stack, the size of which could be controlled at compile-time.

After reduction is finished, `runtime_wasm.reduce` returns an RtTerm using a Uint32Array over the WASM memory, and the term is decompiled using the existing code.

### CODE REVIEW

**Comment by VictorTaelin** [comment]
@michaelforney I'm midway through a big clean-up of the code base, so this will have conflicts. I'll try to resolve them Monday. Very impressive work!

**Comment by michaelforney** [comment]
Merged latest master changes.

**Comment by michaelforney** [comment]
Also pushed a 75-line recursive implementation here: https://github.com/moonad/Formality/compare/master...michaelforney:wasm-recursive

**Comment by VictorTaelin** [comment]
@michaelforney sorry for the delay, will merge it soon.

**Comment by VictorTaelin** [comment]
Closing as it was merged in another PR.

**Pull request closed without merging**
