### PR TITLE
Fix missing implementation and refactor some shifts

### PR DESCRIPTION
**Pull request by elmattic**
This PR mainly fixes implementation of `U8` to `U256` types for the `shl` and `shr` primitives.

It also hides implementation of one-bit shifts into `base/Word/shift_left/` and `base/Word/shift_right/` similarly as for `Word.signed_shift_right`.

### CODE REVIEW

**Comment by elmattic** [comment]
Note that `Word.shift_left.one` and `Word.shift_right.one` are not new algorithms, just renames (I should have use `git mv` really).

**Comment by rigille** [comment]
finishing with `.one` instead of `1` really is more legible

**Comment by elmattic** [comment]
Yes! And thanks for the merge rigille. I'm not sure but I think naming a file `1.kind` is not legit on Windows (likewise `aux.kind`).

**Comment by rigille** [comment]
no need to worry it seems to be legal
https://stackoverflow.com/a/62888

**Pull request merged**
